version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
