version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
    container_name: node-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  volumes:
  mongo_data: